[package]
name = "arrow-examples"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow = { version = "29.0.0", features = ["csv"] }
arrow-csv = "29.0.0"
arrow-flight = "29.0.0"
